"""create analytics schema and tables

Revision ID: 1594d5b9258b
Revises: f5677ecf03d2
Create Date: 2026-08-25 01:07:26.247315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1594d5b9258b"
down_revision: str | Sequence[str] | None = "f5677ecf03d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA analytics")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cost_center", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("code", name="uq_departments_code"),
        sa.UniqueConstraint("cost_center", name=op.f("uq_departments_cost_center")),
        schema="analytics",
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_number", sa.String(length=30), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("job_title", sa.String(length=100), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column(
            "employment_status", sa.String(length=30), server_default="active", nullable=False
        ),
        sa.Column("work_email", sa.String(length=255), nullable=False),
        sa.Column("annual_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["analytics.departments.id"],
            name=op.f("fk_employees_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("employee_number", name="uq_employees_employee_number"),
        sa.UniqueConstraint("work_email", name=op.f("uq_employees_work_email")),
        schema="analytics",
    )
    op.create_table(
        "expense_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_number", sa.String(length=30), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="submitted", nullable=False),
        sa.Column("submitted_date", sa.Date(), nullable=False),
        sa.Column("approved_date", sa.Date(), nullable=True),
        sa.Column("trip_start_date", sa.Date(), nullable=True),
        sa.Column("trip_end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved', 'rejected', 'paid')",
            name=op.f("ck_expense_reports_status_allowed"),
        ),
        sa.CheckConstraint(
            "trip_end_date IS NULL OR trip_start_date IS NULL OR trip_end_date >= trip_start_date",
            name=op.f("ck_expense_reports_trip_date_range_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["analytics.employees.id"],
            name=op.f("fk_expense_reports_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_reports")),
        sa.UniqueConstraint("report_number", name="uq_expense_reports_report_number"),
        schema="analytics",
    )
    op.create_index(
        "ix_expense_reports_employee",
        "expense_reports",
        ["employee_id"],
        unique=False,
        schema="analytics",
    )
    op.create_index(
        "ix_expense_reports_status_date",
        "expense_reports",
        ["status", "submitted_date"],
        unique=False,
        schema="analytics",
    )
    op.create_table(
        "expense_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("merchant", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("receipt_provided", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("reimbursable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('airfare', 'hotel', 'meals', 'ground_transport', "
            "'mileage', 'supplies', 'other')",
            name=op.f("ck_expense_items_category_allowed"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expense_items_amount_positive")),
        sa.CheckConstraint(
            "char_length(currency) = 3", name=op.f("ck_expense_items_currency_length_three")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["analytics.expense_reports.id"],
            name=op.f("fk_expense_items_report_id_expense_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_items")),
        schema="analytics",
    )
    op.create_index(
        "ix_expense_items_category_date",
        "expense_items",
        ["category", "expense_date"],
        unique=False,
        schema="analytics",
    )
    op.create_index(
        "ix_expense_items_report", "expense_items", ["report_id"], unique=False, schema="analytics"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_expense_items_report", table_name="expense_items", schema="analytics")
    op.drop_index("ix_expense_items_category_date", table_name="expense_items", schema="analytics")
    op.drop_table("expense_items", schema="analytics")
    op.drop_index(
        "ix_expense_reports_status_date", table_name="expense_reports", schema="analytics"
    )
    op.drop_index("ix_expense_reports_employee", table_name="expense_reports", schema="analytics")
    op.drop_table("expense_reports", schema="analytics")
    op.drop_table("employees", schema="analytics")
    op.drop_table("departments", schema="analytics")
    op.execute("DROP SCHEMA analytics")
    # ### end Alembic commands ###
