"""create core application tables

Revision ID: f5677ecf03d2
Revises: 7452c28b9a1e
Create Date: 2026-08-20 05:51:59.172312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5677ecf03d2"
down_revision: str | Sequence[str] | None = "7452c28b9a1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "LOCAL_FILESYSTEM",
                "S3_COMPATIBLE",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("source_uri", name=op.f("uq_documents_source_uri")),
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "run_type",
            sa.Enum(
                "ingestion",
                "retrieval",
                "rag",
                "text_to_sql",
                "routing",
                "end_to_end",
                name="evaluation_run_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="evaluation_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("dataset_version", sa.String(length=50), nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("mlflow_run_id", sa.String(length=255), nullable=True),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("parser_name", sa.String(length=100), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.CheckConstraint(
            "file_size_bytes >= 0", name=op.f("ck_document_versions_file_size_nonnegative")
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_document_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "content_hash", name="uq_document_versions_document_hash"
        ),
        sa.UniqueConstraint(
            "document_id", "version_number", name="uq_document_versions_document_version"
        ),
    )
    op.create_index(
        "ix_document_versions_active",
        "document_versions",
        ["document_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_document_versions_content_hash", "document_versions", ["content_hash"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("parent_chunk_id", sa.String(length=64), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("chunk_version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column(
            "section_path",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("element_type", sa.String(length=50), server_default="text", nullable=False),
        sa.Column("table_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "access_control",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(content, ''))", persisted=True),
            nullable=False,
        ),
        sa.CheckConstraint("chunk_version > 0", name=op.f("ck_chunks_chunk_version_positive")),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_chunks_ordinal_nonnegative")),
        sa.CheckConstraint(
            "page_end IS NULL OR page_end > 0", name=op.f("ck_chunks_page_end_positive")
        ),
        sa.CheckConstraint(
            "page_start IS NULL OR page_end IS NULL OR page_end >= page_start",
            name=op.f("ck_chunks_page_range_valid"),
        ),
        sa.CheckConstraint(
            "page_start IS NULL OR page_start > 0", name=op.f("ck_chunks_page_start_positive")
        ),
        sa.CheckConstraint("token_count >= 0", name=op.f("ck_chunks_token_count_nonnegative")),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_chunks_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_chunks_parent_chunk_id_chunks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "document_version_id",
            "ordinal",
            "chunk_version",
            name="uq_chunks_version_ordinal_chunk_version",
        ),
    )
    op.create_index("ix_chunks_content_hash", "chunks", ["content_hash"], unique=False)
    op.create_index(
        "ix_chunks_document_order", "chunks", ["document_version_id", "ordinal"], unique=False
    )
    op.create_index(
        "ix_chunks_search_vector", "chunks", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=True),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "DISCOVERY",
                "VALIDATION",
                "PARSING",
                "CHUNKING",
                "EMBEDDING",
                "INDEXING",
                name="processing_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "QUARANTINED",
                "SKIPPED",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_processing_runs_attempt_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_processing_runs_document_version_id_document_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_runs")),
    )
    op.create_index(
        "ix_processing_runs_status", "processing_runs", ["status", "started_at"], unique=False
    )
    op.create_index(
        "ix_processing_runs_version_stage",
        "processing_runs",
        ["document_version_id", "stage"],
        unique=False,
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("vector", VECTOR(), nullable=False),
        sa.Column("normalized", sa.Boolean(), nullable=False),
        sa.Column("generation_latency_ms", sa.Float(), nullable=True),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("dimensions > 0", name=op.f("ck_embeddings_dimensions_positive")),
        sa.CheckConstraint(
            "generation_latency_ms IS NULL OR generation_latency_ms >= 0",
            name=op.f("ck_embeddings_generation_latency_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_embeddings_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id", "model_name", "model_version", name="uq_embeddings_chunk_model_version"
        ),
    )
    op.create_index("ix_embeddings_chunk_id", "embeddings", ["chunk_id"], unique=False)
    op.create_index(
        "ix_embeddings_model", "embeddings", ["model_name", "model_version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_embeddings_model", table_name="embeddings")
    op.drop_index("ix_embeddings_chunk_id", table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index("ix_processing_runs_version_stage", table_name="processing_runs")
    op.drop_index("ix_processing_runs_status", table_name="processing_runs")
    op.drop_table("processing_runs")
    op.drop_index("ix_chunks_search_vector", table_name="chunks", postgresql_using="gin")
    op.drop_index("ix_chunks_document_order", table_name="chunks")
    op.drop_index("ix_chunks_content_hash", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_document_versions_content_hash", table_name="document_versions")
    op.drop_index("ix_document_versions_active", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_table("evaluation_runs")
    op.drop_table("documents")
    # ### end Alembic commands ###
